import { Aboreto, Inter } from 'next/font/google';
import Header from "../components/header";
import Footer from "../components/footer";
import "./globals.css";

const aboreto = Aboreto({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-aboreto',
})

export const metadata = {
  title: "Ernat",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
    shortcut: "/icon.svg",
    apple: "/icon.svg",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${aboreto.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
